manage_commercial="//a[text()='Manage Commercial']"
dashboard_link='//a[contains(text(),"Dashboard")]'

# Filter
title_commercial="//h3[text()='Manage Commercial']"
airline_input_field="//div[@class='css-1g6gooi']/div/input"
select_airline="//div[contains(@class,'css-15k')]/div/div[@role='option'][1]"
status_input_field="//div[contains(@class,'select-box')]/input"
select_status="//ul[contains(@class,'select-')]/li[1]"
search_button_rule="//button[text()='Search']"
# Add new commercial plan
show_more_button="//div[text()='ShowMore']"
add_new_commercial_icon="//a[@class='floating__icon-link']"
description_input_field="(//fieldset[@class='floating-label']/input)[1]"
priority_input_field="(//fieldset[@class='floating-label']/input)[2]"
air_type_field="(//div[@class='floating-label']/select)[1]"
select_air_type="(//select/option[text()='airtype'])[1]"
search_type_field="(//div[@class='floating-label']/select)[2]"
select_all_search_type="(//select/option[text()='ALL'])[2]"
select_search_type="(//select/option[text()='searchtype'])[1]"
airline_input_field_to_create_plan="(//div[@class='css-1g6gooi']/div/input)[1]"
select_airline_to_create_commercial="(//div[@role='option' and text()='IndiGo'])[1]"
select_enabled_checkbox="(//div[contains(@class,'floating-label-wrapper')]/div/input)[1]"
# Criteria to create commercial plan
inclusion_from_travel_period_input="(//input[@class='form-control'])[1]"
inclusion_to_travel_period_input="//div[@class='relative']/descendant::input"
inclusion_from_booking_period_input="//td[text()='Booking Period']/../descendant::input[1]"
inclusion_to_booking_period_input="//td[text()='Booking Period']/../descendant::input[2]"
exclusion_from_travel_period_input="(//input[@class='form-control'])[3]"
exclusion_to_travel_period_input="(//input[@class='form-control'])[4]"
inclusion_travel_period_icon="(//div[contains(@class,'text-cent')]/button/i)[1]"
exclusion_travel_period_icon="(//div[contains(@class,'text-cent')]/button/i)[3]"
back_month_button="//button[text()='Previous Month']"
next_month_button="//button[text()='Next month']"
calendar_container='//div[@class="react-datepicker__month-container"]'
select_inclusive_date='//div[text()="replacemonth replaceyear"]/parent::div/following::div/div[not(contains(@class,"outside")) and @aria-label="day-replaceday"]'
time_to_replace='//li[contains(@class,"datepicker__time") and text()="timetoreplace"]'
travel_inclusive_from_date_field="(//div[@class='react-datepicker-wrapper'])[1]/div"
travel_inclusive_to_date_field="(//div[@class='react-datepicker-wrapper'])[2]/div"
travel_exclusive_from_date_field="(//div[@class='react-datepicker-wrapper'])[3]/div"
travel_exclusive_to_date_field="(//div[@class='react-datepicker-wrapper'])[4]/div"
booking_period_inclusive_from_date_field="//td[text()='Booking Period']/../descendant::div[@class='react-datepicker-wrapper'][1]/div"
inclusion_booking_period_icon="//td[text()='Booking Period']/../descendant::div[@class='text-center add__datePicker'][1]"
exclusion_booking_period_icon="//td[text()='Booking Period']/../descendant::div[@class='text-center add__datePicker'][2]"
booking_period_inclusive_to_date_field="//td[text()='Booking Period']/../descendant::div[@class='react-datepicker-wrapper'][2]/div"
booking_period_exclusive_from_date_field="//td[text()='Booking Period']/../descendant::div[@class='react-datepicker-wrapper'][3]/div"
booking_period_exclusive_to_date_field="//td[text()='Booking Period']/../descendant::div[@class='react-datepicker-wrapper'][4]/div"
flight_numbers_inclusive_input_field="(//td[text()='Flight Numbers']/../descendant::div/div/input)[1]"
flight_numbers_exclusive_input_field="(//td[text()='Flight Numbers']/../descendant::div/div/input)[2]"
supplier_inclusive_input_field="(//td[text()='Supplier Ids']/../descendant::div/div/input)[1]"
supplier_exclusive_input_field="(//td[text()='Supplier Ids']/../descendant::div/div/input)[2]"
select_supplier_ids="(//td[text()='Supplier Ids']/../descendant::div[@class='css-15k3avv']/div/div)[1]"
sector_inclusive_input_field="(//td[text()='Sector']/../descendant::div/div/input)[1]"
sector_exclusive_input_field="(//td[text()='Sector']/../descendant::div/div/input)[2]"
destination_inclusive_input_field="(//td[text()='Destinations']/../descendant::div/div/input)[1]"
destination_exclusive_input_field="(//td[text()='Destinations']/../descendant::div/div/input)[2]"
airlines_inclusive_input_field="(//td[text()='Air lines']/../descendant::div/div/input)[1]"
airlines_exclusive_input_field="(//td[text()='Air lines']/../descendant::div/div/input)[2]"
fare_basis_inclusive_input_field="(//td[text()='Fare Basis']/../descendant::div/div/input)[1]"
fare_basis_exclusive_input_field="(//td[text()='Fare Basis']/../descendant::div/div/input)[2]"
booking_class_inclusive_input_field="(//td[text()='Booking Class']/../descendant::div/div/input)[1]"
booking_class_exclusive_input_field="(//td[text()='Booking Class']/../descendant::div/div/input)[2]"
operating_carrier_inclusive_input_field="(//td[text()='Operating Carrier']/../descendant::div/div/input)[1]"
operating_carrier_exclusive_input_field="(//td[text()='Operating Carrier']/../descendant::div/div/input)[2]"
private_account_code_inclusive_input_field="(//td[text()='Private Account Codes']/../descendant::div/div/input)[1]"
private_account_code_exclusive_input_field="(//td[text()='Private Account Codes']/../descendant::div/div/input)[2]"
user_id_inclusive_input_field="(//td[text()='User Id']/../descendant::div/div/input)[1]"
select_user_id_inclusion="(//td[text()='User Id']/../descendant::div[contains(@class,'css-15k3avv')]/div/div)[1]"
# user_id_exclusive_input_field="(//td[text()='User Id']/../descendant::div/div/input)[3]"          #QA env
user_id_exclusive_input_field="(//td[text()='User Id']/../descendant::div/div/input)[2]"
pax_type_inclusive_input_field="(//td[text()='Pax Types']/../descendant::div/div/input)[1]"
pax_type_exclusive_input_field="(//td[text()='Pax Types']/../descendant::div/div/input)[3]"
select_pax_type="(//td[text()='Pax Types']/../descendant::div[contains(@class,'css-15k3avv')]/div/div)[1]"
cabin_classes_inclusive_input_field="(//td[text()='Cabin Classes']/../descendant::div/div/input)[1]"
cabin_classes_exclusive_input_field="(//td[text()='Cabin Classes']/../descendant::div/div/input)[3]"
select_cabin_classes="(//td[text()='Cabin Classes']/../descendant::div[contains(@class,'css-15k3avv')]/div/div)[1]"
allow_days_of_week_inclusive_input_field="(//td[text()='Allow Days of week']/../descendant::div/div/input)[1]"
allow_days_of_week_exclusive_input_field="(//td[text()='Allow Days of week']/../descendant::div/div/input)[3]"
select_allow_days="(//td[text()='Allow Days of week']/../descendant::div[contains(@class,'css-15k3avv')]/div/div)[1]"
source_inclusive_input_field="(//td[text()='Source']/../descendant::div/div/input)[1]"
source_exclusive_input_field="(//td[text()='Source']/../descendant::div/div/input)[3]"
select_source="(//td[text()='Source']/../descendant::div[contains(@class,'css-15k3avv')]/div/div)[1]"
fare_type_inclusive_input_field="(//td[text()='Fare Types']/../descendant::div/div/input)[1]"
fare_type_exclusive_input_field="(//td[text()='Fare Types']/../descendant::div/div/input)[3]"
select_fare_type="(//td[text()='Fare Types']/../descendant::div[contains(@class,'css-15k3avv')]/div/div)[1]"
price_range_inclusive_input_field="(//td[text()='Price Range']/../descendant::div/div/input)[1]"
price_range_exclusive_input_field="(//td[text()='Price Range']/../descendant::div/div/input)[2]"

# Commercial Info
commercial_info_plus_icon="(//div[@class='text-right']/button)[index]"
select_commission_type="(//select/option[text()='commission'])[1]"
iata_commission="(//select/option[text()='IATA'])[index]"
plb_commission="(//select/option[text()='PLB'])[index]"
segment_money="(//select/option[text()='Segment Money'])[index]"
markup_commission="(//select/option[text()='Markup'])[index]"
seat_comission="(//select/option[text()='Seat'])[index]"
example_input_field="(//fieldset[@class='floating-label']/input[contains(@placeholder,'Examples:')])[index]"
select_infant_applicable_checkox="(//label[text()='Applicable On Infant'])[index]"
select_applicable_on_all_segment_checkbox="(//label[text()='Applicable On All Segment'])[index]"
select_applicable_on_booking="(//label[text()='Applicable On Booking'])[index]"
submit_button="//button[text()='Submit ']"
cancel_button="//button[text()='Cancel ']"

# Commercial Rule id
get_description="//tbody[@class='table__body-list-font']/tr/td[text()='description']"
commercial_rule_id="//tbody[@class='table__body-list-font']/tr/td[text()='description']//preceding-sibling::td"
delete_icon="//tbody[@class='table__body-list-font']/tr/td[text()='description']//following::td[4]/a/i"   # QA element
# delete_icon="(//div[contains(@class,'floating-label-wrapper')]/div/input)[1]"

delete_button="//button[text()='Delete']"
id_header="//thead[@class='credit_info--header-container ']/tr/td[1]"

