billing_info_field = '//a[text()="Billing Info"]'
generated_from_date = '//input[@name="createdOnAfterDate"]'
generated_to_date = '//input[@name="createdOnBeforeDate"]'
lock_from_date = '//input[@name="lockDateGreaterThan"]'
lock_to_date = '//input[@name="lockDateLessThan"]'
search_btn = '//button[normalize-space()="Search"]'
total_columns = '//thead/tr/td'
payment_due_date_from = '//input[@name="paymentDueDateGreaterThan"]'
payment_due_date_to = '//input[@name="paymentDueDateLessThan"]'
bill_number = '//input[@name="billNumberIn"]'
credit_policy = '//div[text()="Credit Policy"]'
credit_policy_input = '//div[contains(text(),"Credit Policy")]//following::input'
display_total_amt = '//tr[@class="table__row__container  banklist__propper-header-class "]//td[7]'
username = '//div[text()="Username"]'
sales_id = '//div[text()="Sales Id"]'
username_input = '//div[text()="Username"]/../descendant::input'
sales_input = '//div[text()="Sales Id"]/../descendant::input'
sales_selected_id = '//div[@role="option"]'
minimum_age = '//input[@name="ageingMin"]'
maximum_age = '//input[@name="ageingMax"]'
calendar_container = '//div[@class="react-datepicker__month-container"]'
back_month_btn = '//button[text()="Previous Month"]'
table_columns = "//thead/tr/td"
search_card_row_count = "//tbody[contains(@class,'table__body-border')]/tr"
search_card_thead_count="//thead[contains(@class,'theader')]/tr/td"
search_card_tbody_count="//tbody[contains(@class,'table')]/tr"
time_to_replace = '//li[contains(@class,"datepicker__time") and text()="timetoreplace"]'
date_to_be_replaced = '//div[text()="replacemonth replaceyear"]/parent::div/following::div/div[not(contains(@class,"outside")) and @aria-label="day-replaceday"]'
customize_btn = '//span[contains(normalize-space(),"Customize")]'
deselect_all_btn = '//button[@class="btn sign_btn"][text()="De-select All"]'
bill_number_checkbox = '//div[text()="Bill Number"]/input'
settled_amt_checkbox = '//div[text()="Settled Amount"]/input'
settled_date_checkbox = '//div[text()="Settled Date"]/input'
bill_amount = '//div[text()="Bill Amount"]/input'
history_checkbox = '//div[text()="History"]/input'
save_btn = '//button[@class="btn sign_btn"][text()="Save"]'
no_data_found_text = '//h2[@class="table__body-nodata"]'
reset_btn = '//div[@class="custom_btn-container"]//a[@class="btn_reset"]'
popup_reset_btn = '//button[@class="btn sign_btn cancel-btn-generic"]//descendant::i'
cross_icon = '//button[@class="styles_closeButton__20ID4"]'
edit_link = '(//table//thead//td[text()="Edit"]//following::td[text()="Edit"])[1]'
new_lock_date = '//input[@name="newLockDate"]'
next_month_btn = '//button[text()="Next month"]'
update_button = '//button[text()="Update"]'
lock_date = '(//table//thead//td[text()="Lock Date"]//following::tr[1]//td//span)[5]'

